name: todo
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  
  # State management
  get: ^4.6.6
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  
  # Date formatting and internationalization
  intl: ^0.19.0
  
  # Supabase integration
  supabase_flutter: ^2.5.6
  
  # Environment variables
  flutter_dotenv: ^5.1.0

  # Database local con Drift
  drift: ^2.20.2
  sqlite3_flutter_libs: ^0.5.24

  # Red
  dio: ^5.5.0+1

  # OCR on-device
  google_mlkit_text_recognition: ^0.13.0

  # Media
  image_picker: ^1.1.2

  # Animaciones / UI moderna
  lottie: ^3.1.2
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.20.2
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/lottie/study.json
    - assets/lottie/intro-login.json
    - assets/lottie/login.json 
    - assets/lottie/register-animation.json
    
